name: Polymer_Template_Simple
description: A simple Polymer Dart starter application.
dependencies:
  core_elements: any
  intl: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
